name: AgentControl
options:
  bundleIdPrefix: com.agentcontrol
  deploymentTarget:
    macOS: "13.0"
    iOS: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    branch: main

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  # ── macOS target ──────────────────────────────────────
  AgentControlMac:
    type: application
    platform: macOS
    sources:
      - path: Sources/Shared
      - path: Sources/macOS
    resources:
      - path: Resources/Assets.xcassets
    dependencies:
      - package: SwiftTerm
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/AgentControlMac.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.agentcontrol.mac
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ENABLE_APP_SANDBOX: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  # ── iOS target ────────────────────────────────────────
  AgentControliOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/Shared
      - path: Sources/iOS
    resources:
      - path: Resources/Assets.xcassets
    dependencies:
      - package: SwiftTerm
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        INFOPLIST_FILE: Resources/iOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.agentcontrol.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
