name: AgentControlMac
options:
  bundleIdPrefix: com.agentcontrol
  deploymentTarget:
    macOS: "13.0"
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    branch: main

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  AgentControlMac:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Resources/Assets.xcassets
    dependencies:
      - package: SwiftTerm
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/AgentControlMac.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.agentcontrol.mac
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ENABLE_APP_SANDBOX: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
